[versions]
# Check for latest at https://fabricmc.net/develop/
loom = "1.17.3"

[plugins]
loom-gradle = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
