[versions]
# Check for latest at https://maven.architectury.dev/dev/architectury/loom/dev.architectury.loom.gradle.plugin
loom = "1.16.1"

[plugins]
loom-gradle = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }