[versions]
# Check for latest at https://maven.architectury.dev/architectury-plugin/architectury-plugin.gradle.plugin
architectury-gradle = "3.5-SNAPSHOT"

# Check for latest at https://maven.architectury.dev/dev/architectury/loom/dev.architectury.loom.gradle.plugin
architectury-loom = "1.14-SNAPSHOT"

[plugins]
architectury-gradle = { id = "architectury-plugin", version.ref = "architectury-gradle" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }