[versions]
slf4j-api = "2.0.17"
jetbrains-annotations = "26.1.0"

fastutil-concurrent-wrapper = "0.2.3"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api"}
jetrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

fastutil-concurrent-wrapper = { module = "com.trivago:fastutil-concurrent-wrapper", version.ref = "fastutil-concurrent-wrapper" }